package com.east.identitycard.entity;
// Generated Jun 15, 2015 4:30:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IdentityCard generated by hbm2java
 */
@Entity
@Table(name = "identity_card", catalog = "test", uniqueConstraints = @UniqueConstraint(columnNames = "ID_NUMBER"))
public class IdentityCard implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3371456398073232785L;
	private Integer id;
	private String idNumber;
	private String nationality;
	private String issuingAuthority;
	private String firstname;
	private String lastname;
	private String fullname;
	private String gender;
	private Date dateOfBirth;
	private Date creationDate;
	private Date expirationDate;
	private ResidenceAddress residenceAddress;

	public IdentityCard() {
	}

	public IdentityCard(String idNumber, String nationality,
			String issuingAuthority, String firstname, String lastname,
			String fullname, String gender, Date dateOfBirth,
			Date creationDate, Date expirationDate) {
		this.idNumber = idNumber;
		this.nationality = nationality;
		this.issuingAuthority = issuingAuthority;
		this.firstname = firstname;
		this.lastname = lastname;
		this.fullname = fullname;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.creationDate = creationDate;
		this.expirationDate = expirationDate;
	}

	public IdentityCard(String idNumber, String nationality,
			String issuingAuthority, String firstname, String lastname,
			String fullname, String gender, Date dateOfBirth,
			Date creationDate, Date expirationDate,
			ResidenceAddress residenceAddress) {
		this.idNumber = idNumber;
		this.nationality = nationality;
		this.issuingAuthority = issuingAuthority;
		this.firstname = firstname;
		this.lastname = lastname;
		this.fullname = fullname;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.creationDate = creationDate;
		this.expirationDate = expirationDate;
		this.residenceAddress = residenceAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ID_NUMBER", unique = true, nullable = false, length = 20)
	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	@Column(name = "NATIONALITY", nullable = false)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "ISSUING_AUTHORITY", nullable = false)
	public String getIssuingAuthority() {
		return this.issuingAuthority;
	}

	public void setIssuingAuthority(String issuingAuthority) {
		this.issuingAuthority = issuingAuthority;
	}

	@Column(name = "FIRSTNAME", nullable = false, length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", nullable = false, length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "FULLNAME", nullable = false, length = 100)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "GENDER", nullable = false, length = 5)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_OF_BIRTH", nullable = false, length = 19)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRATION_DATE", nullable = false, length = 19)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "identityCard")
	public ResidenceAddress getResidenceAddress() {
		return this.residenceAddress;
	}

	public void setResidenceAddress(ResidenceAddress residenceAddress) {
		this.residenceAddress = residenceAddress;
	}

}
